fixtures:
  repositories:
    epel: "https://github.com/stahnma/puppet-module-epel.git"
    python: "https://github.com/stankevich/puppet-python.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    systemd: "https://github.com/camptocamp/puppet-systemd"
  symlinks:
    supervisord: "#{source_dir}"
